import { presetUno, presetAttributify, presetIcons } from 'unocss';
import Unocss from 'unocss/vite';

const colors = ['primary', 'warning', 'danger', 'success', 'waiting'];
const safelist = [
  'bg-primary',
  'bg-danger',
  'bg-warning',
  'bg-default',
  'bg-success',
  'text-primary',
  'text-danger',
  'text-warning',
  'text-default',
  'text-success',
  'border-primary',
  'border-danger',
  'border-warning',
  'border-default',
  'border-success',
  'hover:bg-hover-primary',
  'hover:bg-hover-danger',
  'hover:bg-hover-warning',
  'hover:bg-hover-success',
  'hover:border-hover-primary',
  'hover:border-hover-danger',
  'hover:border-hover-warning',
  'hover:border-hover-success',
  'hover:text-hover-primary',
  'hover:text-hover-danger',
  'hover:text-hover-warning',
  'hover:text-hover-success',
  ...colors.map((v) => `border-${v}-400`),
  ...colors.map((v) => `border-${v}-500`),
  ...colors.map((v) => `text-${v}-500`),
  ...colors.map((v) => `hover:text-${v}-500`),
  'text-white',
  ...Array.from({ length: 8 }, (_, i) => `px-${i + 1}`),
  ...Array.from({ length: 8 }, (_, i) => `py-${i + 1}`),
  ...['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl'].map((v) => `text-${v}`),
  ...['rounded-full', 'rounded-lg'],
  ...['search', 'edit', 'check', 'message', 'star-off', 'delete', 'add', 'share'].map((v) => `i-ic-baseline-${v}`),
];

export default () =>
  Unocss({
    presets: [presetUno(), presetAttributify(), presetIcons()],
    safelist,
    rules: [
      ['bg-primary', { 'background-color': '#5e7ce0' }],
      ['bg-danger', { 'background-color': '#f66f6a' }],
      ['bg-warning', { 'background-color': '#fac20a' }],
      ['bg-success', { 'background-color': '#50d4ab' }],
      ['bg-default', { 'background-color': '#ffffff' }],
      ['border-primary', { 'border-color': '#5e7ce0' }],
      ['border-danger', { 'border-color': '#f66f6a' }],
      ['border-warning', { 'border-color': '#fac20a' }],
      ['border-success', { 'border-color': '#50d4ab' }],
      ['border-default', { 'border-color': '#ffffff' }],
      ['text-primary', { color: '#5e7ce0' }],
      ['text-danger', { color: '#f66f6a' }],
      ['text-warning', { color: '#fac20a' }],
      ['text-success', { color: '#50d4ab' }],
      ['text-default', { color: '#ffffff' }],
      ['bg-hover-primary', { 'background-color': '#7693f5' }],
      ['bg-hover-danger', { 'background-color': '#ff7875' }],
      ['bg-hover-warning', { 'background-color': 'rgba(250, 194, 10, .8)' }],
      ['bg-hover-success', { 'background-color': 'rgba(80, 212, 171, .8)' }],
      ['border-hover-primary', { 'border-color': '#7693f5' }],
      ['border-hover-danger', { 'border-color': '#ff7875' }],
      ['border-hover-warning', { 'border-color': 'rgba(250, 194, 10, .8)' }],
      ['border-hover-success', { 'border-color': 'rgba(80, 212, 171, .8)' }],
      ['text-hover-primary', { color: '#7693f5' }],
      ['text-hover-danger', { color: '#ff7875' }],
      ['text-hover-warning', { color: 'rgba(250, 194, 10, .8)' }],
      ['text-hover-success', { color: 'rgba(80, 212, 171, .8)' }],
    ],
  });
